### ISSUE TITLE
Add pixelNeRF to the repository

### ISSUE THREAD

**Issue by mihaimorariu** [pfnet/pynif3d#5]
The pixelNeRF paper will be added to the repository: https://arxiv.org/abs/2012.02190

**Tasks to be completed**
- [x] Implement DTU dataset loader
- [x] Implement the encoder
- [x] Implement the NIF model
- [x] Implement the renderer
- [x] Implement the pipeline
- [x] Implement the losses
- [x] Write tutorial on how to use the code
- [ ] Review

**Definition of Done**
- [x] The results are reproduced
- [x] Training, evaluation scripts are provided
- [x] Tutorial is provided
